### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by iamalperen** [cardinal-labs/cardinal-namespaces#182]
https://github.com/cardinal-labs/cardinal-namespaces/blob/1f2086398db2dbdd8230e0fc4a4eb19a9f2547d2/src/utils.ts#L63

Hey! There is a try catch in this function and it is logging error as a string to console. So we are not able to catch this error in this way. Can you remove the try catch or throw an error in catch state instead of logging string? Otherwise console is full of strings not  catchable errors.

**Comment by gchatz22** [comment]
I don't think we want to be throwing an error in this occasion, as the function is trying to get the name and if it does not exist it will just return undefined. It should be fine if you would want to remove the log from there however to not show in the console

**Comment by iamalperen** [comment]
Then we can remove the log if not want to throw an error. But there is an error in there and we are not able to catch it from our side. Just see a console log. This is not reasonable imo

**Comment by iamalperen** [comment]
So what is your suggestion then? What can we do? Will we remove the console.log(error) or remove the try catch? Logging an error string that cannot be caught from our side is not reasonable and just a mess in console.

**Comment by gchatz22** [comment]
apologies on not following up here, removed log and pushed new version `4.1.57`.
https://github.com/cardinal-labs/cardinal-namespaces/commit/837938c28abb99094d26c194f7d46fe6b84c9710
https://www.npmjs.com/package/@cardinal/namespaces

**Comment by iamalperen** [comment]
Thanks a lot
