### ISSUE TITLE
Can you upgrade to @solana/spl-token please?

### ISSUE THREAD

**Issue by GHesericsu** [cardinal-labs/cardinal-namespaces#95]
Hi this is Eric from Jet Protocol and I'm trying to integrate our latest release with the Dialect team. Can I ask you to upgrade to @solana/spl-token 0.2.0 please? Token is not a class anymore in the newest version of @solana/spl-token. Actions are exported separately. https://github.com/solana-labs/solana-program-library/issues/2953#issuecomment-1053845582

But here, this is still using the Token class and is causing issues in not just our project. 

https://github.com/cardinal-labs/cardinal-namespaces/blob/4c6257c91cb3341678de7be3d34cb09d91ce4b9f/src/instructions.ts#L215

**Comment by jpbogle** [comment]
hey @GHesericsu ya we can upgrade to splToken 0.2.0 most people are on 0.1.8

This shouldnt be a blocker though regardless. It should be because the dependency is ^0.1.8 which resolves up to 0.2.0 they definitely shouldve made it a full version bump given the backwards incompaitibility

**Comment by GHesericsu** [comment]
https://github.com/jet-lab/jet-app/tree/v2 < (v2 branch)To duplicate the issue: import `import { defaultVariables, IncomingThemeVariables, NotificationsButton } from '@dialectlabs/react-ui';` and `npm run start:legacy`

I have tried the alias method and deleted our @solana/spl-token  but it didn't work.

**Comment by GHesericsu** [comment]
Thanks for being so responsive! @jpbogle

**Comment by jpbogle** [comment]
hey @GHesericsu maybe I am missing something but I cloned, ran 

`git clone https://github.com/jet-lab/jet-app.git`
`npm install`
`npm run start` 

and it works in the UI and I was able to create message thread

`npm run start:legacy` shows this
```
jbogle|JBMP~/C/jet-app (:master)> npm run start:legacy                                                                                                                                                                                       16:44:54

> start:legacy
> NODE_OPTIONS=--openssl-legacy-provider craco start

node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by GHesericsu** [comment]
@jpbogle You have to use to v2 branch here https://github.com/jet-lab/jet-app/tree/v2

**Comment by GHesericsu** [comment]
Appreciate you checking on this :)

**Comment by GHesericsu** [comment]
Our v1 master doesn’t have any issue as everything is using spl-token0.1.8 there.

**Comment by jpbogle** [comment]
hmm sorry I tried v2 and dont see any issues running the app, is there something I should try on the app once its running. Maybe screenshots of pasting your package-lock.json could help because mine shows no usage of dialect or cardinal but the dependencies look right. Basically we can update this to spl-token@.2.0 but also I don't see why it shouldnt work given that many other dependencies in jet are using 0.1.8 :)

**Comment by GHesericsu** [comment]
Hi @jpbogle  

To duplicate the issue: import import { defaultVariables, IncomingThemeVariables, NotificationsButton } from '@dialectlabs/react-ui'; in `src//components/NavBar.tsx` and npm run start:legacy

But the good news is I actually solved the issue by upgrading @dialectlabs/react-ui to the latest, using @solana/spl-token@0.1.8, and using spl-token 0.2.0 as an alias. Also fiddled around with deleting both node-modules and package-lock.json. Sorry for the trouble. 

The current package-lock.json that's working. 

![Screen Shot 2022-07-14 at 1 37 45 AM](https://user-images.githubusercontent.com/60202455/178860144-9687de09-9422-4891-8997-76537239c7a4.png)

**Comment by GHesericsu** [comment]
Thank you for your time! Sorry about the trouble.
